### ISSUE TITLE
Illegal readlink option

### ISSUE THREAD

**Issue by jonatan-ivanov** [weibemoura/asdf-groovy#3]
If I run `groovy -version`, I'm getting an error:
```
❯ groovy -version                                                                                                                   
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
groovy: JAVA_HOME is not defined correctly, can not execute: //bin/java
```

As far as I remember, it worked previously, it seems that the root cause is the [exec-env](https://github.com/weibemoura/asdf-groovy/blob/master/bin/exec-env#L2) script:
`JAVA_HOME=$(realpath $(dirname $(readlink -f $(asdf which java)))/../)`
(change: https://github.com/weibemoura/asdf-groovy/commit/8a637ad8fa34cb9d9fa310dcb4ae4ffd1204b166#diff-e1d721568af624d970ad38a0165ecfb2)

I'm not sure if this is really needed, asdf-java now supports setting `JAVA_HOME` without restarting the shell: https://github.com/halcyon/asdf-java/issues/51

I'm using oh-my-zsh on MacOS.

**Comment by weibemoura** [comment]
Please update your plugin and then try to install again

**Comment by weibemoura** [comment]
Please update your plugin and then try to install again

**Comment by jonatan-ivanov** [comment]
@weibemoura Seems good, thanks

For the record, since this was fixed without a PR, here's the fix: https://github.com/weibemoura/asdf-groovy/commit/b752405fecc5ad3cbae9522c89c8dd6c9e9319fe

P.S.: @weibemoura Don't you want to get the advantage of PRs so that changes and issues could be more trackable?

**Comment by jonatan-ivanov** [comment]
I have another question, maybe it would worth a separate issue: this plugin now overwrites the `JAVA_HOME` what do you think about being able to turn this logic off (via an env var) so that it cannot conflict with other things, e.g.: asdf-java sets `JAVA_HOME` too.

**Comment by weibemoura** [comment]
Thanks @jonatan-ivanov  we can work together on this question what do you think about sending a pull request?

Does your JAVA_HOME variable come from the asdf-java plugin? In had should continue with the same value see https://github.com/halcyon/asdf-java/blob/master/set-java-home.bash

**Comment by jonatan-ivanov** [comment]
Sounds great, I can create a PR.

`set-java-home.bash` is exactly what I use (see my opening comment). I think there are a few use-cases which could be covered:
- No `JAVA_HOME`  at all (no `set-java-home.bash` or custom script) so that asdf-groovy needs to set `JAVA_HOME`
- `set-java-home.bash` is used, in this case, asdf-groovy does not need to do anything
- A custom script is used to set `JAVA_HOME`, in this case, asdf-groovy does not need to do anything

I'm not sure how the third one is really a use-case if it is not it's enough checking if `asdf_update_java_home` is present or not. If it is a valid use-case, I think it would worth introduce an env var to make the logic switchable (e.g.: `ASDF_GROOVY_EXPORT_JAVA_HOME`)
