### ISSUE TITLE
Runtime issue

### ISSUE THREAD

**Issue by AxelRHD** [weibemoura/asdf-groovy#5]
I just installed Groovy 3.0.4 with ASDF. Reshim afterwards and make it global.

Trying to execute a simple Hello.groovy script with the content `println "Hello world.` throws `unknown command: java. Perhaps you have to reshim?`

This can be skipped with a Keypress and then the code is executed. But I can't figure out the main problem. Of course JAVA is installed (/usr/bin/java).

Have you any idea?

Thank you.

**Comment by weibemoura** [comment]
Did you install Java directly through the operating system's package manager or via ASDF?
Do you have the JAVA_HOME environment variable set?

Remove the plugin and install again

**Comment by AxelRHD** [comment]
Thank you for the quick response.

Java is installed with OS package manager /usr/bin/java is linked via /etc/alternatives to an /opt directory. JAVA_HOME is not set.

Do I understand you correctly: the JAVA_HOME has to be set before plugin installation? So where should it point to? /usr/bin /etc... or /opt...?

**Comment by weibemoura** [comment]
Remove the asdf-groovy plugin and then install again.

As you installed Java directly by the OS you must set JAVA_HOME to the root directory of JDK/JRE, in some distributions the directory is in /usr/lib /jvm.
