### ISSUE TITLE
ASDF_GROOVY_DISABLE_JAVA_HOME_EXPORT unbound variable in strict mode

### ISSUE THREAD

**Issue by bdellegrazie** [weibemoura/asdf-groovy#9]
Hi @weibemoura ,

We're using asdf in strict mode and recently the plugin has started erroring with:
```shell
direnv: loading ~/.asdf/plugins/groovy/bin/exec-env
./exec-env:3: ASDF_GROOVY_DISABLE_JAVA_HOME_EXPORT: unbound variable
```
This line in `exec-env` :
```
  if [[ ! ("$ASDF_GROOVY_DISABLE_JAVA_HOME_EXPORT" = true) ]]; then
``
should probably be something like (YMMV):
```
  if [[ ! ("${ASDF_GROOVY_DISABLE_JAVA_HOME_EXPORT:-}" == "true") ]]; then
```

**Comment by weibemoura** [comment]
thanks @bdellegrazie, the exec-env script has been updated with your suggestion
